name: Build Prod

on:
  push:
    branches:
      - gh-pages
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: 显示环境变量
        run: |
          echo "环境变量：$SSH_HOST"
      - name: 登录服务器拉取镜像并运行
        if: env.SSH_HOST != ''
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ vars.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          command: |
            echo "拉取镜像成功"
