name: Build Prod

on:
  push:
    branches:
      - gh-pages
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FTP_HOST: ${{ secrets.FTP_HOST }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: 初始化 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 安装依赖
        run: |
          npm i
          echo "success"
      - name: 发布内容
        if: env.FTP_HOST != ''
        run: |
          node ./.build/publish.js
        env:
          FTP_HOST: ${{secrets.FTP_HOST}}
          FTP_PORT: 21
          FTP_USER: ${{secrets.FTP_USER}}
          FTP_PWD: ${{secrets.FTP_PWD}}
