name: Build Prod

on:
  push:
    branches:
      - gh-pages
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive repository
        run: |
          tar czvf repository.tar.gz autobot autobot_doc autojs index.html
          ls -al

      - name: 拷贝文件到远程服务器
        uses: lengxing-lx/scp-remote-action@v1.1
        if: env.SERVER_HOST != ''
        with:
          ipaddr: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          operation_type: upload
          operation_list: |
            file repository.tar.gz /www/wwwroot/mobile.tntok.top
      - name: 登录到目标服务器解压部署
        uses: appleboy/ssh-action@master
        if: env.SERVER_HOST != ''
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /www/wwwroot/mobile.tntok.top
            rm -rf ./autobot
            rm -rf ./autobot_doc
            rm -rf ./autojs
            ls -al
            tar xzf repository.tar.gz
            ls -al

      - name: SyncGitee
        if: env.SSH_PRIVATE_KEY != ''
        run: |
          # 同步sshkey以访问私有仓库
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa gitee.com >> ~/.ssh/known_hosts
          # 进入到上级目录
          mkdir static_demo
          cd static_demo
          # clone远程仓库到当前目录
          git clone git@gitee.com:fuckshit/static_demo.git .
          ls -l
