name: Build Prod

on:
  push:
    branches:
      - gh-pages
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive repository
        run: |
          tar czvf repository.tar.gz autobot autobot_doc autojs
          ls -al

      - name: Copy to server
        uses: appleboy/scp-action@master
        if: env.SERVER_HOST != ''
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./autobot/*,./autobot_doc/*,./autojs/*"
          target: /www/wwwroot/doc.tntok.top

          # source: "repository.tar.gz"
          # - name: SSH into server
      #   uses: appleboy/ssh-action@master
      #   if: env.SERVER_HOST != ''
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     script: |
      #       cd /www/wwwroot/doc.tntok.top
      #       ls -al
      #       tar xzf repository.tar.gz
